// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvrvqrpeficvllaqyvhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cnZxcnBlZmljdmxsYXF5dmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzI5MjAsImV4cCI6MjA2NTMwODkyMH0.DxoaFCdrEXJ8f19rcCHAcibvBPE-9ApAHyvpyMfAb10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);